version: '3.8'

services:
  ollama:
    build: ./ollama
    container_name: ollama
    networks:
      - cleitin_net
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  fastapi-app:
    build: ./app
    container_name: fastapi_app
    networks:
      - cleitin_net
    depends_on:
      - ollama
    environment:
      - OLLAMA_API=http://ollama:11434
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    # command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  ollama_data:

networks:
  cleitin_net:
    driver: bridge
